[package]
name = "aperture"
description = "Aperture programming language"
license = "MIT"
version = "0.15.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
colored = "2.1.0"
toml = "0.8.19"
unicode-xid = "0.2.5"

