[config]
# number of lines to show before and after the error line
# set to -1 to disable snippets
snippet = 1
# allow side effectus
# if false: disables: mutability, modality, publicity and other sources of side effects
side_effects = true
# disable the standard library
disable_std = false
# disable the standard library prelude
load_std = true
