[package]
name = "ape_parser"
description = "syntax analysis for Aperture programming language"
license="MIT"
version = "0.1.6"
edition = "2021"

[dependencies]
ape_ast = "0.1.3"
ape_errors = "0.1.2"
ape_lexer = "0.1.3"
