[package]
name = "ape_bundler"
description = "crate bundlers for Aperture programming language"
license = "MIT"
version = "0.1.1"
edition = "2021"

[dependencies]
ape_ast = "0.1.6"
ape_errors = "0.1.4"
ape_lexer = "0.1.8"
ape_parser = "0.1.7"
