[package]
name = "ape_lexer"
description = "lexical analysis for Aperture programming language"
license="MIT"
version = "0.1.9"
edition = "2021"

[dependencies]
ape_ast = "0.1.3"
ape_errors = "0.1.1"
